### ISSUE TITLE
`build': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by enginecan** [bootstrap-email/bootstrap-email#233]
### What version of Bootstrap Email are you using?

1.4.0

### How are you compiling?

Ruby

### Code example

Hey, I am getting this error. Any idea what's causing this?

### Describe your issue

`"/usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/converters/body.rb:8:in `build': undefined method `[]' for nil:NilClass (NoMethodError)\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/converters/base.rb:14:in `build'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/compiler.rb:72:in `compile_html'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/compiler.rb:34:in `perform_html_compile'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/bootstrap_email_cli.rb:91:in `public_send'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/lib/bootstrap-email/bootstrap_email_cli.rb:91:in `<top (required)>'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/bin/bootstrap-email:4:in `require_relative'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/gems/bootstrap-email-1.4.0/bin/bootstrap-email:4:in `<top (required)>'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/bin/bootstrap-email:23:in `load'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/bin/bootstrap-email:23:in `<main>'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'\n\tfrom /usr/local/rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'\n"\\\`

**Comment by stuyam** [comment]
Could you share a bit more about your setup and maybe some code examples so I may be able to help you better? Maybe the HTML you are trying to run this on also?

**Comment by aneshodza** [comment]
I am also getting this. Anything new?

**Comment by MineKing9534** [comment]
I also get this error, but only when running the command using a gradle task. When executing `bootstrap-email` manually everything works fine but using a `Exec` gradle task that should automate the building process I get this error
